# Generated by Django 3.2.5 on 2021-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210811_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pictures/default_picture.jpg', upload_to='images/profile_pictures/'),
        ),
    ]
