# Generated by Django 3.2.5 on 2021-08-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pictures/default_picture.jpg', upload_to='images/profile_pictures'),
        ),
    ]
