# Generated by Django 3.2.5 on 2021-08-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image'),
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
    ]
