# Generated by Django 3.2.4 on 2021-08-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_id'),
        ('accounts', '0009_auto_20210829_0008'),
    ]

    operations = [
    ]
