# Generated by Django 3.2.4 on 2021-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_0009_alter_profile_id_0009_auto_20210829_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile_pictures', verbose_name='Аватар'),
        ),
    ]
