# Generated by Django 3.2.5 on 2021-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
