# Generated by Django 3.2.5 on 2021-07-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210731_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Наклейка', 'verbose_name_plural': 'Наклейки'},
        ),
    ]
