# Generated by Django 3.2.5 on 2021-08-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Наклейка', 'verbose_name_plural': 'Наклейки'},
        ),
    ]
