# Generated by Django 3.2.4 on 2021-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_0011_auto_20210829_0008_0011_auto_20210830_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/images/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_p',
            field=models.ImageField(blank=True, upload_to='media/images/products/%Y/%m/%d'),
        ),
    ]
