# Generated by Django 3.2.5 on 2021-08-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
