# Generated by Django 3.2.4 on 2021-08-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210829_0008'),
        ('orders', '0007_auto_20210830_1046'),
    ]

    operations = [
    ]
